
def main():
    startApplication("GeomApp")
    clickButton(waitForObject(":Operations.New part_AppElements_Button"))
    clickTab(waitForObject(":General.qt_tabwidget_tabbar_QTabBar"), "Sketch")
    clickButton(waitForObject(":Basic.Sketch_AppElements_Button"))
    mouseClick(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 446, 299, 0, Qt.LeftButton)
    clickButton(waitForObject(":Basic.Line_AppElements_Button"))
    mouseClick(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 378, 243, 0, Qt.LeftButton)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonPress, 377, 365, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonRelease, 377, 365, Qt.LeftButton, 0, 0)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonPress, 735, 367, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonRelease, 735, 367, Qt.LeftButton, 0, 0)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonPress, 730, 235, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonRelease, 730, 235, Qt.LeftButton, 0, 0)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonPress, 378, 243, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonRelease, 378, 243, Qt.LeftButton, 0, 0)
    clickButton(waitForObject(":Basic_QToolButton_2"))
    clickTab(waitForObject(":General.qt_tabwidget_tabbar_QTabBar"), "Construction")
    clickTab(waitForObject(":General.qt_tabwidget_tabbar_QTabBar"), "Features")
    clickButton(waitForObject(":Basic.Extrusion_AppElements_Button"))
    mouseClick(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 443, 317, 0, Qt.LeftButton)
    mouseDrag(waitForObject(":From.qt_spinbox_lineedit_QLineEdit"), 36, 8, -77, 0, 1, Qt.LeftButton)
    clickButton(waitForObject(":Extrusion.property_panel_ok_QToolButton"))
    clickTab(waitForObject(":General.qt_tabwidget_tabbar_QTabBar"), "Sketch")
    clickButton(waitForObject(":Basic.Sketch_AppElements_Button"))
    mouseClick(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 524, 318, 0, Qt.LeftButton)
    clickButton(waitForObject(":Basic.Line_AppElements_Button"))
    mouseClick(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 379, 219, 0, Qt.LeftButton)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonPress, 380, 357, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonRelease, 380, 357, Qt.LeftButton, 0, 0)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonPress, 822, 358, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonRelease, 822, 358, Qt.LeftButton, 0, 0)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonPress, 812, 222, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonRelease, 812, 222, Qt.LeftButton, 0, 0)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonPress, 379, 219, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonRelease, 379, 219, Qt.LeftButton, 0, 0)
    clickButton(waitForObject(":Basic_QToolButton_2"))
    clickTab(waitForObject(":General.qt_tabwidget_tabbar_QTabBar"), "Construction")
    clickTab(waitForObject(":General.qt_tabwidget_tabbar_QTabBar"), "Features")
    clickButton(waitForObject(":Basic.Extrusion_AppElements_Button"))
    mouseClick(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 429, 273, 0, Qt.LeftButton)
    type(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), "<Control>")
    mouseDrag(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 601, 443, 6, -260, 67108866, Qt.RightButton)
    mouseDrag(waitForObject(":From.qt_spinbox_lineedit_QLineEdit"), 37, 7, -81, 0, 1, Qt.LeftButton)
    type(waitForObject(":From.from_size_ModuleBase_ParamSpinBox"), "<Keypad_2>")
    type(waitForObject(":From.from_size_ModuleBase_ParamSpinBox"), "<Keypad_0>")
    type(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), "<Control>")
    mouseDrag(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 496, 435, -9, -36, 67108866, Qt.RightButton)
    clickButton(waitForObject(":Extrusion.property_panel_ok_QToolButton"))
    type(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), "<Control>")
    mouseDrag(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 381, 228, -18, 64, 67108866, Qt.RightButton)
    clickTab(waitForObject(":General.qt_tabwidget_tabbar_QTabBar"), "Sketch")
    clickButton(waitForObject(":Basic.Sketch_AppElements_Button"))
    mouseClick(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 104, 264, 0, Qt.LeftButton)
    clickButton(waitForObject(":Basic.Circle_AppElements_Button"))
    mouseClick(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 14, 134, 0, Qt.LeftButton)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonPress, 406, 322, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonRelease, 406, 322, Qt.LeftButton, 0, 0)
    clickButton(waitForObject(":Basic_QToolButton_2"))
    clickTab(waitForObject(":General.qt_tabwidget_tabbar_QTabBar"), "Features")
    clickButton(waitForObject(":Basic.Extrusion_AppElements_Button"))
    mouseClick(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 88, 539, 0, Qt.LeftButton)
    type(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), "<Control>")
    mouseDrag(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 377, 440, -13, -247, 67108866, Qt.RightButton)
    mouseDrag(waitForObject(":To.qt_spinbox_lineedit_QLineEdit"), 59, 7, -96, 5, 1, Qt.LeftButton)
    type(waitForObject(":To.to_size_ModuleBase_ParamSpinBox"), "<Keypad_5>")
    mouseDrag(waitForObject(":From.qt_spinbox_lineedit_QLineEdit"), 140, 17, -184, -9, 1, Qt.LeftButton)
    type(waitForObject(":From.from_size_ModuleBase_ParamSpinBox"), "<Keypad_5>")
    openContextMenu(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 272, 543, 0)
    mouseDrag(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 362, 470, 68, -29, 67108866, Qt.RightButton)
    clickButton(waitForObject(":Extrusion.property_panel_ok_QToolButton"))
    
    clickButton(waitForObject(":Basic.Boolean_AppElements_Button"))
    mouseClick(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 559, 339, 0, Qt.LeftButton)
    type(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), "<Shift>")
    mouseClick(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 922, 350, 33554432, Qt.LeftButton)
    mouseClick(waitForObject(":Boolean.Selected objects:_QListWidget"), 122, 110, 0, Qt.LeftButton)
    type(waitForObject(":Boolean.Selected objects:_QListWidget"), "<Shift>")
    mouseClick(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 158, 374, 33554432, Qt.LeftButton)
    clickButton(waitForObject(":Boolean.property_panel_ok_QToolButton"))
    
    clickTab(waitForObject(":General.qt_tabwidget_tabbar_QTabBar"), "Sketch")
    clickButton(waitForObject(":Basic.Sketch_AppElements_Button"))
    mouseClick(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 597, 321, 0, Qt.LeftButton)

    clickButton(waitForObject(":Basic.Circle_AppElements_Button"))
    mouseClick(waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), 127, 232, 0, Qt.LeftButton)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonPress, 188, 274, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonRelease, 188, 274, Qt.LeftButton, 0, 0)
    clickButton(waitForObject(":Basic_QToolButton_2"))
    
    clickTab(waitForObject(":General.qt_tabwidget_tabbar_QTabBar"), "Features")
    clickButton(waitForObject(":Basic.Extrusion_AppElements_Button"))

    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonPress, 188, 274, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_ViewPort"), QEvent.MouseButtonRelease, 188, 274, Qt.LeftButton, 0, 0)

    sendEvent("QCloseEvent", waitForObject(":OpenParts v.1.1.0*_AppElements_MainWindow"))
    clickButton(waitForObject(":Save current file.Close without Saving_QPushButton"))
